language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t pacog/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pacog/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-React-env"
  bucket_name: "elastic_us-west-2...."
  bucket-path: "docker-react"
  on:
    branch: master
  access_ley_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"